### PR TITLE
feat: add preview button show all effects at one

### PR DESCRIPTION
**Pull request by marcjal**
## Checklist

- [x] I ran `npm test` locally and it passed without errors.

- [x] I only edited the `_data/pixels.json` file.

- [x] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

### CODE REVIEW

**Comment by marcjal** [comment]
> Hey @marcjal it seems like you are adding the `_site` folder with this pull request. That directory is intentionally ignored by git using the `.gitignore` file because it will be generated by Netlify during the deployment process. Could you please revert those changes? Thank you for your contribution!

@dkundel Sorry! I wanna add a functionality to party-mode.js file. Is possible to add a functionality there? I don't see the correct way to add it.

**Comment by dkundel** [comment]
There is one version of the `party-mode.js` in `assets/javascript/party-mode.js` that you can edit. It will automatically be copied into `_site` during deployment

**Comment by marcjal** [comment]
> There is one version of the `party-mode.js` in `assets/javascript/party-mode.js` that you can edit. It will automatically be copied into `_site` during deployment

Thanks @dkundel can you re-review?

**Comment by marcjal** [comment]
> Yeah this is great! Since this seems to just run all of them after each other maybe calling this `Run All (a)` makes more sense. Also can we run `reset` as the last one so it's back to normal after that?

Sure @dkundel! Let me see that

**Comment by marcjal** [comment]
> Yeah this is great! Since this seems to just run all of them after each other maybe calling this `Run All (a)` makes more sense. Also can we run `reset` as the last one so it's back to normal after that?

Done! Also, I made a rebase. Can you re-review, please?

**Pull request merged**
