### PR TITLE
feat(pixels): add my new pixel

### PR DESCRIPTION
**Pull request by lindsayh-git**
## Checklist

- [ x ] I ran `npm test` locally and it passed without errors.

- [ x ] I only edited the `_data/pixels.json` file.
- [ x  ] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

### CODE REVIEW

**Comment by lindsayh-git** [comment]
I'm new to this, so forgive me for any ignorance, but it appears to be a
server-side heap issue that's at the root of the failure - versus the
simplistic code change I pushed. Is that a fair statement?

Cheers.

Lindsay

**Comment by dkundel** [comment]
Hi @lindsayh-git yes there seems to be something wrong with the integration but also you are claiming a pixel that has already been claimed. Can you please try to find one that is still available?

**Comment by lindsayh-git** [comment]
I did take a pixel. I couldn't see any unclaimed ones.  Will try and figure
it out today!

**Comment by lindsayh-git** [comment]
Committed a merge which hopefully resolves the matter

**Comment by lindsayh-git** [comment]
Seems like the heap error is reoccurring - causing code review to fail.

**Comment by dkundel** [comment]
Yeah there seems to be some heap issue with Danger & GitHub Actions right now. I'll merge it manually. Thanks for picking another pixel :)

**Pull request merged**
