### PR TITLE
feat(pixels): Added new pixel

### PR DESCRIPTION
**Pull request by thomaswells**
## Checklist

- [x] I ran `npm test` locally and it passed without errors.
- [x] I only edited the `_data/pixels.json` file.
- [x] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../../LICENSE.md).

### CODE REVIEW

**Comment by dkundel** [comment]
Hey @thomaswells please don't delete the unclaimed pixels :)

**Comment by thomaswells** [comment]
Sorry about that. I _think_ I fixed it.

**Comment by dkundel** [comment]
Seems like there's been a bunch of contributions since then that are causing a merge conflict. Can you [sync your fork](https://help.github.com/en/articles/syncing-a-fork) and push merges to your branch. That should make this contribution ready.

Let me know if you are stuck anywhere.

**Comment by dkundel** [comment]
GitHub got confused so I helped out with the last part :) should be good now!

**Comment by thomaswells** [comment]
Third time is the charm, maybe? I've not actually used github much.  So I know I didn't handle the sync / merge conflict quite right. :(

**Pull request merged**
