### PR TITLE
All contributors/add amykapernick

### PR DESCRIPTION
**Pull request by GabrielRamaldes**
## Checklist

- [x] I ran `npm test` locally and it passed without errors.

- [ x I only edited the `_data/pixels.json` file.

- [x] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

### CODE REVIEW

**Comment by GabrielRamaldes** [comment]
Hello, i am a newbie GitHub user, i want to correct the errors above. How do i do it?

**Comment by SoftCreatR** [comment]
@GabrielRamaldes Please check out https://github.com/twilio-labs/open-pixel-art/blob/master/CONTRIBUTING.md to learn, how to contribute to the project (and also, how not to do it).

**Comment by GabrielRamaldes** [comment]
> @GabrielRamaldes Please check out https://github.com/twilio-labs/open-pixel-art/blob/master/CONTRIBUTING.md to learn, how to contribute to the project (and also, how not to do it).

I read it and tried to follow the steps but it didn't work. The problem is i need to fix this pull request to keep going in TwilioQuest (i am at the Contributing to Open Source: Merging! mission and specifically asks me to merge this pull request). Is there any way for me to do that?

image

**Comment by dkundel** [comment]
Hi @GabrielRamaldes! It seems like you opened a PR from the wrong branch/repository. If you go to the previous objective inside TwilioQuest there should be a link that you can click to create the right PR. We also created a walkthrough video that might help you. https://youtu.be/ghYg42YOvHE

**Comment by dkundel** [comment]
I'll close this PR in the meantime since you'll have to create a new one

**Comment by GabrielRamaldes** [comment]
> Hi @GabrielRamaldes! It seems like you opened a PR from the wrong branch/repository. If you go to the previous objective inside TwilioQuest there should be a link that you can click to create the right PR. We also created a walkthrough video that might help you. https://youtu.be/ghYg42YOvHE

image

I am trying to create the right pull request, but i keep receiving this message. Can i proceed?

**Comment by dkundel** [comment]
Ah so I just looked at your branch: https://github.com/GabrielRamaldes/open-pixel-art/tree/new-pixel and it seems like the branch got messed up. Try running the following things:
```bash
git checkout master
git checkout -b new-pixel-attempt-two
npm run sync-fork
```

Then go into `_data/pixels.json` and add your pixel and savee the file. Run:
```bash
npm test
git add _data/pixels.json
git commit -m "feat(pixels): add my pixel"
npm run sync-fork
git push origin new-pixel-attempt-two
```

And then create a PR where the last dropdown is for `new-pixel-attempt-two`. That should hopefully work

**Comment by GabrielRamaldes** [comment]
> Ah so I just looked at your branch: https://github.com/GabrielRamaldes/open-pixel-art/tree/new-pixel and it seems like the branch got messed up. Try running the following things:
> 
> ```shell
> git checkout master
> git checkout -b new-pixel-attempt-two
> npm run sync-fork
> ```
> 
> Then go into `_data/pixels.json` and add your pixel and savee the file. Run:
> 
> ```shell
> npm test
> git add _data/pixels.json
> git commit -m "feat(pixels): add my pixel"
> npm run sync-fork
> git push origin new-pixel-attempt-two
> ```
> 
> And then create a PR where the last dropdown is for `new-pixel-attempt-two`. That should hopefully work

Thank you! It works now 😄

**Pull request closed without merging**
