### PR TITLE
feat(pixels) add my new pixel

### PR DESCRIPTION
**Pull request by polivierstpch**
## Checklist

- [ x ] I ran `npm test` locally and it passed without errors.

- [ x ] I only edited the `_data/pixels.json` file.

- [ x ] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [ x ] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

### CODE REVIEW

**Comment by polivierstpch** [comment]
@dkundel The CI seems to not be working properly, as when I checked the logs, it said I deleted an entry in the pixels.json file, but it is still here! Any idea how to fix this?

**Comment by dkundel** [comment]
Yeah @polivierstpch I unfortunately noticed but haven't found a solution yet :( I described more of the issue in #2046 and will try to see if I can find a solution this week. But if someone wants to work on that I'd be happy to merge the fix

**Comment by dkundel** [comment]
I'll review the PRs manually later

**Comment by tesla809** [comment]
@dkundel would you be able to review #2158 ?
The CI is failing due to an issue with the `danger` diff.

See: https://github.com/twilio-labs/open-pixel-art/issues/2046

**Pull request merged**
