### PR TITLE
feat(pixels): add my new pixel

### PR DESCRIPTION
**Pull request by msandfor**
## Checklist

- [X] I ran `npm test` locally and it passed without errors.

- [X] I only edited the `_data/pixels.json` file.

- [X] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [X] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

### CODE REVIEW

**Review by amykapernick — CHANGES_REQUESTED** [review]
Looks like you're missing the commas at the end of lines 53 to 55, can you add them back in?

**Review by msandfor — COMMENTED** [review]
Fixed missing comma's

**Review by msandfor — COMMENTED** [review]
reordered wars pixel

**Review by amykapernick — APPROVED** [review]

**Review by amykapernick — CHANGES_REQUESTED** [review]
Looks like there's a missing like for the pixel in (4, 1) as well (was line 9 of the file), can you add that back?

**Review by msandfor — COMMENTED** [review]
added unclaimed pixel in

**Pull request merged**
