### PR TITLE
feat(pixels): add my new pixel

### PR DESCRIPTION
**Pull request by DrMyuu**
## Checklist

- [x] I ran `npm test` locally and it passed without errors.

- [x] I only edited the `_data/pixels.json` file.

- [x] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../../LICENSE.md).

### CODE REVIEW

**Comment by DrMyuu** [comment]
Can someone help me with what I am doing wrong?

**Comment by DrMyuu** [comment]
Twilio Quest is saying that 844 does not belong to my account?

**Comment by dkundel** [comment]
This is a known bug. The usernames in GitHub for TwilioQuest are currently case sensitive. @rmkubik can you point @DrMyuu how to fix this?

**Comment by dkundel** [comment]
Also your PR is right it's just out-of-date. Some pixels have been merged since then. We are trying to improve that but for now I'll just merge your PR.

**Comment by DrMyuu** [comment]
Thank you so much!

**Comment by rmkubik** [comment]
Sorry about this TwilioQuest bug! We’re going to address that in a new version soon! 

In the meantime, you should be able to return to the previous objective you set your username in and update it to match the casing of your GitHub user name. Or, you can edit the TwilioQuest environment variables directly from the Settings menu in the Environment tab.

**Pull request merged**
