### PR TITLE
Update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**
## Checklist

- [ ] I ran `npm test` locally and it passed without errors.

- [ ] I only edited the `_data/pixels.json` file.

- [ ] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Please take a look here: https://github.com/twilio-labs/open-pixel-art/blob/master/CONTRIBUTING.md#documentation-contribution-guidelines

**Comment by dkundel** [comment]
Thank you for opening the PR @sakshamtaneja21 and thank you referencing the PR contributing guides @SoftCreatR! Our CoC right now is based on the Contributor Covenant and the comma setting there seems appropriate so I'll close this one. Thank you!

**Comment by sakshamtaneja21** [comment]
ok

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Pull request closed without merging**
