### PR TITLE
Add Feature: Colorized Name

### PR DESCRIPTION
**Pull request by Shaedil**
## Checklist

- [ ] I ran `npm test` locally and it passed without errors.
- [ ] I only edited the `_data/pixels.json` file.
- [ ] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../../LICENSE.md).

## Description

Obtains the color from the pixel and checks if its contrast is above 50%. If it is, then contributor-name is colored accordingly. Otherwise, the default color is used.

## Related issues

Issue #217

### CODE REVIEW

**Comment by dkundel** [comment]
Hey @Shaedil I checked https://deploy-preview-277--pixel-project-dev.netlify.com/ and it doesn't seem to be working? Also @M0nica since you suggested the feature do you want to review this?

**Comment by Shaedil** [comment]
Hey @dkundel thanks for replying. I was (and still am) away from my dev machine when I created the pull request so, I am not able to test the code. Would you mind if I use this pull request and its preview feature just to test some things?

**Comment by dkundel** [comment]
Sure as long as you are not overdoing it :)

**Comment by dkundel** [comment]
Actually it seems like @Shaedil this was solved in #284 already as part of a new tooltip feature. I really appreciate your PR though!

**Pull request closed without merging**
