### PR TITLE
open-pizel-art

### PR DESCRIPTION
**Pull request by the-grinder126**
## Checklist

- [x] I ran `npm test` locally and it passed without errors.

- [x] I only edited the `_data/pixels.json` file.

- [x] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

add my new pixel (33, 28) (#cfa96e)

### CODE REVIEW

**Comment by gustavolabela** [comment]
new-pixel

**Comment by bolas444** [comment]
add my new pixel (#4323)

**Comment by Nimdy** [comment]
new-pixel

**Comment by Klickrr** [comment]
add my pixel #15919f

**Pull request closed without merging**
