### PR TITLE
feat(pixels): add my new pixel (3,7)

### PR DESCRIPTION
**Pull request by rittmang**
## Checklist

- [x] I ran `npm test` locally and it passed without errors.

- [x] I only edited the `_data/pixels.json` file.

- [x] I entered the `username` in the `pixels.json` that I'm also using to create this pull request.
- [x] I acknowledge that all my contributions will be made under the project's [license](../../LICENSE.md).

### CODE REVIEW

**Comment by rittmang** [comment]
The 2 usernames mentioned are indeed included in my version of the pixels.json

**Comment by jaredpsimpson** [comment]
This the failure:

"It seems like you are accidentally deleting some contributions of others. Please make sure you have pulled the latest changes from the master branch and resolved any merge conflicts. https://help.github.com/en/articles/syncing-a-fork
 
Make sure that the following usernames are indeed included: Kiy4h,okoronen"

**Comment by rittmang** [comment]
Yes, I've checked. Those usernames do feature in my file as well.

**Comment by jaredpsimpson** [comment]
This is the one in master that I didn't see in the file that you are merging:

    {"y": 28, "x": 7, "color": "#ffffff", "username": "okoronen"},

**Pull request merged**
