### PR TITLE
Update mock-fS to 5.1.2

### PR DESCRIPTION
**Pull request by mpomery**
## Checklist

- [x] I ran `npm test` locally and it passed without errors.
- [x] I acknowledge that all my contributions will be made under the project's [license](../LICENSE).

## Description

Updated the version of mock-fs being used to the latest 5.1.2
Several people in the TwilioQuest discord have hit issues running the tests locally getting output such as
```
> open-pixel-art@1.0.0 test
> jest

 FAIL  __tests__/scripts/mergePixels.test.js
  ● getSortedPixelsFromFile › returns already sorted
    EBADF: bad file descriptor, read

  ● getSortedPixelsFromFile › sorts file if necessary
    EBADF: bad file descriptor, read

  ● run › handles conflict with same coordinates by shifting branch contribution
    EBADF: bad file descriptor, read

  ● run › handles conflict with different pixels by merging
    EBADF: bad file descriptor, read

  ● run › handles conflict with reordering changes
    EBADF: bad file descriptor, read
```
They have likely installed the latest LTS of NodeJS v16
With the older version of Mock-FS this was working on NodeJS 14 (now maintenance LTS)

I've tested this change locally on the latest LTS v14 and LTS v16 release and tests pass successfully on both.

## Related issues
https://discord.com/channels/570292611215130634/804374967714054144/929850582527774771
https://discord.com/channels/570292611215130634/804374967714054144/930562234562797668
https://discord.com/channels/570292611215130634/804374967714054144/930681677628452885

### CODE REVIEW

**Comment by mpomery** [comment]
It looks like the automated builds will also need to be updated. They are currently running Node.JS v10.

**Comment by mpomery** [comment]
@dkundel the mergify config also needs updating so you weren't automatically pinged for this PR

**Comment by mpomery** [comment]
Made what I think was the required change to Mergify (but it uses the config from master to prevent people from being able to force-merge code) and updated the version of Node used for Github Actions which ran successfully

**Comment by rmkubik** [comment]
Dominik is moving off of maintaining this project. I can merge this PR if it's ready though! Is it ready for merging?

**Comment by mpomery** [comment]
It should be ready for merging. Tests pass, Mergify config is valid, build failed as expected because files other than `_data/pixels.json` were modified.

With Dominik moving off this project it might be good to remove him from the Mergify config so he doesn't get pinged on Github automatically
see:
https://github.com/twilio-labs/open-pixel-art/blob/master/.mergify.yml#L26
https://github.com/twilio-labs/open-pixel-art/blob/master/.mergify.yml#L35

**Pull request merged**
